name: Deploy API

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAMESPACE: vinaykudari
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vinaykudari
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute Docker image, service name, and tags
        id: meta
        run: |
          # Sanitize branch to a valid docker repo component (lowercase, no slashes)
          SANITIZED=$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9._-]+#-#g' | sed -E 's#^-+|-+$##g')
          # Extract project-name (tail segment of the branch), then sanitize for Koyeb service names
          RAW_TAIL="${BRANCH_NAME##*/}"
          PROJECT_NAME=$(echo "${RAW_TAIL}" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9._-]+#-#g' | sed -E 's#^-+|-+$##g')
          IMAGE="${DOCKER_NAMESPACE}/${SANITIZED}"
          TAGS="${IMAGE}:latest"
          SERVICE_NAME="awake-lauraine/${PROJECT_NAME}"
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "service_name=${SERVICE_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Install Koyeb CLI
        run: |
          curl -L https://github.com/koyeb/koyeb-cli/releases/download/v5.5.1/koyeb-cli_5.5.1_linux_amd64.tar.gz -o koyeb.tar.gz
          tar -xzf koyeb.tar.gz
          sudo mv koyeb /usr/local/bin/koyeb

      - name: Redeploy service on Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN_API }}
        run: |
          echo "Redeploying ${{ steps.meta.outputs.service_name }} with image ${{ steps.meta.outputs.image }}:latest"
          # Assumes the Koyeb service ${SERVICE_NAME} is already configured to use this image tag
          koyeb service redeploy "${{ steps.meta.outputs.service_name }}" --token "${KOYEB_TOKEN}"
